from dotenv import load_dotenv
import os

load_dotenv()
class Config:
     #CLAVE PARA LA CONFIGURACION DE FLASK
    SECRET_KEY=os.getenv('SECRET_KEY','')

    #CLAVE SECRETA PARA CONFIGURACION DE ACCESS_TOKENS
    TOKEN_SECRET_KEY=os.getenv('TOKEN_SECRET_KEY','')

    #CONFIGURACION BASE DE DATOS
    DB_HOST=os.getenv('DB_HOST','')
    DB_NAME=os.getenv('DB_NAME','')
    DB_PORT=os.getenv('DB_PORT','')
    DB_USER=os.getenv('DB_USER','')
    DB_PASSWORD=os.getenv('DB_PASSWORD','')

    #ESQUEMA CONTENEDOR DE LA APLICACION
    SCHEMA='AGROENLACE'
    
    #TABLAS A DISPOSICION EN LA BASE DE DATOS
    T_USER='USUARIO'
    T_ROL ='ROL'
    T_BITACORA='BITACORA'
    T_ORDEN='ORDEN_TRABAJO'
    T_TERRENO='TERRENO'
    T_CAMPANA='CAMPANA_CULTIVO'
    T_MAQUINA='MAQUINARIA'

    
    T_TRANSACCION_COMERCIAL = 'TRANSACCION_COMERCIAL'
    T_RUTA='RUTA_LOGISTICA'
    T_NIVEL_FIDELIZACION='NIVEL_FIDELIZACION'
    T_REGLA_FIDELIZACION='REGLA_FIDELIZACION'
    T_DESCUENTO_TRANSACCION='DESCUENTO_TRANSACCION'

    #ROLES
    CLIENT_ROLE_ID=4
    ADMIN_ROLE_ID=1
    EMPLOYEE_ROLE_ID=3
    SUP_ROLE_ID=2
