-- Migracion: HU28 - Programa de Fidelizacion de Clientes CRM
-- Ejecutar antes de seed_fidelizacion.sql

CREATE TABLE IF NOT EXISTS AGROENLACE.NIVEL_FIDELIZACION (
    ID_NIVEL             SERIAL PRIMARY KEY,
    NOMBRE_NIVEL         VARCHAR(80) NOT NULL,
    DESCRIPCION          TEXT,
    MIN_TRANSACCIONES    INTEGER DEFAULT 0,
    MIN_MONTO_ACUMULADO  NUMERIC(12, 2) DEFAULT 0,
    PRIORIDAD            INTEGER DEFAULT 1,
    ESTADO               VARCHAR(20) DEFAULT 'ACTIVO',
    ID_EMPRESA           INTEGER NOT NULL REFERENCES AGROENLACE.empresa(ID_EMPRESA),
    CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AGROENLACE.REGLA_FIDELIZACION (
    ID_REGLA              SERIAL PRIMARY KEY,
    ID_NIVEL              INTEGER NOT NULL REFERENCES AGROENLACE.NIVEL_FIDELIZACION(ID_NIVEL),
    TIPO_TRANSACCION      VARCHAR(50) DEFAULT 'PEDIDO_INSUMO',
    PORCENTAJE_DESCUENTO  NUMERIC(5, 2) DEFAULT 0,
    MONTO_MAX_DESCUENTO   NUMERIC(12, 2),
    VIGENCIA_DESDE        DATE,
    VIGENCIA_HASTA        DATE,
    ESTADO                VARCHAR(20) DEFAULT 'ACTIVO',
    CREATED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AGROENLACE.DESCUENTO_TRANSACCION (
    ID_DESCUENTO          SERIAL PRIMARY KEY,
    NRO_TRANSACCION       INTEGER NOT NULL REFERENCES AGROENLACE.TRANSACCION_COMERCIAL(NRO_TRANSACCION),
    ID_CLIENTE            INTEGER NOT NULL REFERENCES AGROENLACE.USUARIO(ID_USUARIO),
    ID_NIVEL              INTEGER REFERENCES AGROENLACE.NIVEL_FIDELIZACION(ID_NIVEL),
    ID_REGLA              INTEGER REFERENCES AGROENLACE.REGLA_FIDELIZACION(ID_REGLA),
    SUBTOTAL_ORIGINAL     NUMERIC(12, 2) NOT NULL,
    PORCENTAJE_DESCUENTO  NUMERIC(5, 2) DEFAULT 0,
    DESCUENTO_TOTAL       NUMERIC(12, 2) DEFAULT 0,
    MONTO_FINAL           NUMERIC(12, 2) NOT NULL,
    CREATED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE AGROENLACE.NIVEL_FIDELIZACION IS 'Niveles de fidelizacion CRM por empresa';
COMMENT ON TABLE AGROENLACE.REGLA_FIDELIZACION IS 'Reglas de descuento asociadas a niveles de fidelizacion';
COMMENT ON TABLE AGROENLACE.DESCUENTO_TRANSACCION IS 'Trazabilidad del descuento aplicado a transacciones comerciales';
