-- Migracion: HU27 - Gestion de Rutas y Logistica de Distribucion
-- Tabla: RUTA_LOGISTICA

CREATE TABLE IF NOT EXISTS AGROENLACE.RUTA_LOGISTICA (
    ID_RUTA                 SERIAL PRIMARY KEY,
    ID_TRANSACCION          INTEGER NOT NULL REFERENCES AGROENLACE.TRANSACCION_COMERCIAL(NRO_TRANSACCION),
    ID_CHOFER               INTEGER NOT NULL REFERENCES AGROENLACE.USUARIO(ID_USUARIO),
    ID_EMPRESA              INTEGER NOT NULL REFERENCES AGROENLACE.empresa(ID_EMPRESA),
    ORIGEN                  VARCHAR(255) NOT NULL,
    DESTINO                 VARCHAR(255) NOT NULL,
    FECHA_ASIGNACION        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ENTREGA_ESTIMADA  DATE NOT NULL,
    FECHA_ENTREGA_REAL      TIMESTAMP,
    ESTADO                  VARCHAR(50) DEFAULT 'ASIGNADA',
    OBSERVACIONES           TEXT,
    URL_EVIDENCIA_IMAGEN    TEXT,
    URL_EVIDENCIA_AUDIO     TEXT,
    CREATED_AT              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE AGROENLACE.RUTA_LOGISTICA IS 'Rutas de distribucion para entrega de pedidos';
COMMENT ON COLUMN AGROENLACE.RUTA_LOGISTICA.ESTADO IS 'ASIGNADA, ENTREGADA, CANCELADA';
